showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
theme: 1
mixinText: |
  mixin: 
     mixed-port: 7890
     allow-lan: true
     mode: Rule
     log-level: info
     ipv6: false
     external-controller: '127.0.0.1:9090'
     hosts:
       'router.asus.com': 192.168.186.1
       'gist.github.com': 52.69.186.44
     dns:
       enable: true
       listen: 127.0.0.1:53
       ipv6: false
       enhanced-mode: fake-ip # fake-ip 或 redir-host
       nameserver-policy:
          # 百度公共DNS 180.76.76.76
          '*.baidu.com': 180.76.76.76
          '*.tw': 1.1.1.1
          # 谷歌公共DNS 8.8.8.8
          'testflight.apple.com': 8.8.8.8
          'duckduckgo.com': 8.8.8.8
          'stackoverflow.com': 8.8.8.8
          # 阿里公共DNS 223.5.5.5
          '*.tmall.com': 223.5.5.5
          '*.taobao.com': 223.5.5.5
          '*.alicdn.com': 223.5.5.5
          '*.aliyun.com': 223.5.5.5
          '*.alipay*.com': 223.5.5.5
          '*.alibaba*.com': 223.5.5.5
          '*.alimama*.com': 223.5.5.5
          # 腾讯公共DNS 119.29.29.29
          '*.qq.com': 119.29.29.29
          '*.tencent.com': 119.29.29.29
          '*.weixin.com': 119.29.29.29
          '*.qpic.cn': 119.29.29.29
          '*.jd.com': 119.29.29.29
          '*.bilibili.com': 119.29.29.29
          'hdslb.com': 119.29.29.29
          '*.163.com': 119.29.29.29
          '*.126.com': 119.29.29.29
          '*.126.net': 119.29.29.29
          '*.127.net': 119.29.29.29
          '*.netease.com': 119.29.29.29
          '*.10010.com': 119.29.29.29
          '*.unicompayment.com': 119.29.29.29
          '*.ximalaya.com': 119.29.29.29
          '*.bdstatic.com': 119.29.29.29
          '*.mianbaoduo.com': 119.29.29.29
          '*.unipus.cn': 119.29.29.29
          '*.chaoxing.com': 119.29.29.29
          '*.cnblogs.com': 119.29.29.29
          '*.archlinux.org': 119.29.29.29
          '*.weixin.qq.com': 119.29.29.29
       default-nameserver:
         - 223.5.5.5
         - 119.29.29.29
         - 8.8.8.8
       nameserver:   
         - tls://223.5.5.5:853
         - tls://dot.pub:853
       fallback:   
         - https://rubyfish.cn/dns-query # or use https://1.0.0.1/dns-query 
         - https://public.dns.iij.jp/dns-query 

       fallback-filter:
         geoip: true
         geoip-code: CN
         ipcidr:
           - 240.0.0.0/4
           - 0.0.0.0/32
           - 127.0.0.1/32
         domain:
           - +.google.com
           - +.facebook.com
           - +.youtube.com
           - +.vimeo.com
           - +.xn--ngstr-lra8j.com
           - +.google.cn
           - +.googleapis.cn
connProxy: 2
editProfileWithCFWEditor: true
unsafeURLsText: |
  urls: # array
systemTheme: false
